name: Python package

on: [push]

env:
  python-version: "3.7"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with ruff
        run: |
          # default set of ruff rules with GitHub Annotations
          ruff --format=github  .

      - name: Test with pytest
        run: |
          pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to the dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app_python:latest