- name: Ping all hosts
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

- name: Deploy typescript web_app
  hosts: all
  become: yes
  roles:
    - web_app
  vars:
    app_name: typescript_app
    container_name: react_swapi
    image: "kurohata7/react_swapi"
