apiVersion: v1
kind: Secret
metadata:
  name: helm-secret
  labels:
    app: app-py-helm
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote}}
