- name: Ping all hosts
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

- name: Deploy web_app rust
  hosts: all
  become: yes
  roles:
    - web_app
  vars:
    app_name: rust_app
    container_name: moscow_time_rust
    image: "el3os/moscow_time_rust"
