version: '3'
services:
  web_app:
    container_name: app_python
    image: bobievnodir/app_python:latest
    ports:
        - 5000:5000
    environment:
        - TZ=UTC
    volumes:
      - data:/data

volumes:
  data: