version: "3"

services:
  app_python:
    container_name: app_python
    image: nzgeg3s0/doe-lab2
    ports:
      - 8080:8000
    volumes:
      - visits:/app/src/data
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  visits: {}