apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-msk-time
  labels:
    app: python-msk-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-msk-time
  template:
    metadata:
      labels:
        app: python-msk-time
    spec:
      containers:
        - name: python-msk-time
          image: kurohata7/devops_msk_time
          ports:
            - containerPort: 5000
