apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-msk-time-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: python-msk-time.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-msk-time-service
                port:
                  number: 5000
