files: ^app_python/
repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args: ["-c", "app_python/pyproject.toml"]
      additional_dependencies: [ "bandit[toml]" ]
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: ["--config", "app_python/pyproject.toml"]
- repo: https://github.com/psf/black.git
  rev: 23.7.0
  hooks:
  - id: black
    args: ["--config", "app_python/pyproject.toml"]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--settings-path", "app_python/pyproject.toml"]