repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.0.290
    hooks:
      - id: ruff