apiVersion: v1
kind: Service
metadata:
  name: app-kotlin
spec:
  type: NodePort
  selector:
    app: app-kotlin
  ports:
    - nodePort: 31686 # access service via this port
      port: 8080 # internally in cluster
      targetPort: 8080 # container listening