apiVersion: v1

kind: Service

metadata:
  name: app-go-service
  labels:
    app: app-go

spec:
  type: LoadBalancer
  selector:
    app: app-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
