apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-js
  labels:
    app: js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: js
  template:
    metadata:
      labels:
        app: js
    spec:
      containers:
      - name: app-js
        image: kernie/joke-js
        ports:
        - containerPort: 3000
