replicaCount: 3

image:
  repository: edikgoose/base-converter
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: [ ]

volumeMounts:
  - name: app-data-kotlin
    mountPath: app/sources

volumeClaimTemplates:
  - metadata:
      name: app-data-kotlin
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 62Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }
