password: ENC[AES256_GCM,data:210xfjv9PM0vRGdE1SaBt+kD,iv:Ld6h+oSaufsWKrleIGHDPusnjZZX+qjTKoo79fN7MRY=,tag:R3g1FVlD5TjQMlDUcFWEQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-13T17:51:51Z"
    mac: ENC[AES256_GCM,data:H4QQXb+I7PQ0n7Ovc1kv9KVm9dWjzyw87Y3hUT0CzLhFQyqTHdkQkXzGzRg75Z4LJ/2gT5RNSjDQA7fdsrVtVeb5QhAjze76uaNM9uQsLQXLMoBzqWqQUfAuLqunk16p+ium0vR40Q79rFtzcEodrPoDweaWe0h9bFh+Gm7FAXw=,iv:wguHuZWJY7Z3OAC6iuC86oZinA/NWb0RomcbRrqERZ8=,tag:QrHUruPawH4G1w2CQF+iXg==,type:str]
    pgp:
        - created_at: "2023-11-13T17:51:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYf5FFOT6ELwSAQdADYm/rR1E1xDgFICcMESJ3g5vxQnpxjT05LLcaCR5+icw
            H9Qa6gPZ3BjqvIQBIh6s1JTH8r3uFuBM0i77aNCRs4xcrAVK/TqVu6a6Vk3p6Eyp
            1GYBCQIQgxDvBMMXILBxKh3Iaff5AubL6ciYEFNsc7IrksOGAeSvnQbVigDXPWZA
            DrN4DH+GGLhUzFiFC+p1X29VnX5uCMa5zHEwCmMXCosJQRmVk2vxhAp9bCMHRrvn
            CUzheK92Xfs=
            =raPF
            -----END PGP MESSAGE-----
          fp: 66F23BF842EBA942D17338CC91D1FB25F6F4C3F6
    unencrypted_suffix: _unencrypted
    version: 3.8.1
