secret: ENC[AES256_GCM,data:xm58dd00Q1X/mA==,iv:fzBv3l8S9ABb/SIyFzjJmTnf2DYQZtsUv6SjflD4W0s=,tag:3uf/hMlhERQlW/Lr69yCNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T20:30:48Z"
    mac: ENC[AES256_GCM,data:5xCjr+UU+Qr1AvIt89XheZJeZ/7c/9mHxJ01XDU8HeSpwTa9CIfwioUMx6fZUBhW41ULc2rOR7P1cUqjof21WPSMv7M0riDQZWueuCcwVXntGPpiSoN6sJs+KuifJ+aVCT82BtG14txOqx34I8tvpd8iNDPPu13X4h/N2k4YnJ4=,iv:KNpECFYPrt8dHIM8PPfqOuiewvAGnwg0lxXIcLF6MIw=,tag:+Z6YjHoDOhFiXbFiA5NBkw==,type:str]
    pgp:
        - created_at: "2023-11-14T20:29:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA8FPluxxaWfbAQv9HGlrdtq6lht6OCf/BX/XJFgeeP0PF7fuqVR3jcBdGnp+
            XcYOXigq5mw23DYQO33ddRptRVbWgqK45KeCynDJsFOW/hyUDdAcFIHvV6D9LPao
            DPkDgJqPvlPR+3rszy0VX5Y4jxyEKJhTsyf1GhM2T21w3OIx6IQ/MhrJ8wu2CZXo
            P2UDPdsLokgtsDdU53HpImmBnn1yF+KmOhPi40INsMJnxSf+8LQRDz/IiE9Hhiat
            PwiM/KNceDJudPGAfxMCet0f541eK886HxGko+ey3CqQn2XcoTGvfjqcM7mTu0Yg
            yNOwYfas5bNIvQSPow/oeqPCUrrXWQDAXRFbU8ZbLN18ERz4sOnIiQIvQpih15Su
            RcnwvzOLDGz+2Itt61VcnBeESt1wzoxem/yXLuJgV9w7UVh75jRKODUuUtm0tp0J
            smcLbPyTRvxLragXJjNX22Y5bnr8itVHhDA+6ezFDBiQrjH2Y/wac/vfrxzyMPC/
            ybxT/EJdAPfT5Pv/FZ1v0lwB75mwXdUFOzcqO08aQX3S9uf6gLDoy9SApMlNVV7r
            ISq38X/zf7aDsHGg3cZpF39BzKd40VhEginAxEo2gsbPeaySHzffXO++prcBXcaM
            t6sw9S1zRMkxwwhXpg==
            =FEdt
            -----END PGP MESSAGE-----
          fp: 85C9DB5BD6BD6641CA3BBF2706561221CC0CD477
    unencrypted_suffix: _unencrypted
    version: 3.8.1
