secret: ENC[AES256_GCM,data:5FVVbUYzGBSwuAGYEj7hF207Mw==,iv:H0BGRv+Cf977WqU7V3Yq5mTCkKpAsQ2j/OcZkbkfAnE=,tag:+tr3TX3Tn61aGvUSvraSPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T20:45:20Z"
    mac: ENC[AES256_GCM,data:v/gd3eMVlfv9gL870mfJQdJ+o09+BO86/xw9cfjxdGiMqiVnL8uJ/IHe7+eCfsJqaN/6Vbb1rqf05ImmLUcTiFYD44oXBnJm6nuZJPxX2maY7iZW+7MA2Kazas7NAN4YL7KBfltMDsxDbzTY7gHQYqkRiDLYT+n3JqQ+aKVOnbM=,iv:IHNWfXJOMxZmjKI6PMunTMKDQaWDZGMuJdwaEIFCN0E=,tag:Rgn2vHjxe2uLZv2VNvui/A==,type:str]
    pgp:
        - created_at: "2023-11-14T20:44:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dcp+vHzM6AvgSAQdANGYzaeEruEGOKyEShvewUEWW/abajuiCTd5qB1in6lww
            YdfXMuXoDt0JkV8flLYC6eWWMxvinzdQgacZe215OB6UuMTRRDNt6geGKytvvY3U
            1GgBCQIQL7+bLAXeFRXD4j8V+7kQEtIfc4CQnYvf7mtQsUqYRtQjSpuxxyKaFotE
            SDHKDGCdIfhr+cw/++Fq9M+X+D1inJ3F4YwcZ+P7YVmc6VSCMviTJyez1RJvL3Tl
            yBEIMbGJxM/Tjw==
            =e7uM
            -----END PGP MESSAGE-----
          fp: 580AE1A86009202012C52203F4057F1E29847380
    unencrypted_suffix: _unencrypted
    version: 3.8.1
