- name: deploy role
  tags: deploy_process
  block:
    - name: Create directory for the {{app_name}} container
      file:
        path: "/{{app_name}}"
        state: directory

    - name: Copy Docker compose
      template:
        src: docker-compose.yml.j2
        dest: "/{{app_name}}/docker-compose.yml"

    - name: Run Docker compose
      shell: "cd /{{app_name}} && docker-compose -p {{ app_name }} up -d"
