---
- name: Ensure that deps are installed and run image.
  block:
    - name: Ensure that deps are installed.
      apt:
        name:
          - docker
        state: present
      tags:
        - deps
    - name: Run the app.
      docker_container:
        name: "{{ app_name}}"
        image: "{{ image_name }}:latest"
        ports:  "{{ ports }}"
      tags: 
        - run

- name: Create a directory for docker-compose if it does not exist.
  file:
    path: "/tmp/{{ image_name }}"
    state: directory

- name: Deliver docker compose to the host.
  template:
    src: docker-compose.yml.j2
    dest: "/tmp/{{ image_name }}/docker-compose.yml"

- include_tasks: wipe.yml
  when: web_app_full_wipe | bool
  tags: 
    - wipe