---
- name: Deploy web app docker container
  block:
    - name: Wipe web app
      tags: wipe
      include_tasks: wipe_web_app.yml
    - name: Deploy web app
      tags: deploy
      include_tasks: deliver_docker_compose_file.yml
...