- name: Pull image and run container
  community.docker.docker_container:
    name: docker_web_app
    image: '{{ docker_image }}'
    exposed_ports:
      - 7098
    published_ports:
      - 7098:7098
    platform: linux/amd64
