---
- name: Target
  debug:
    var: web_app_full_wipe
- name: Setup web app
  import_tasks: run.yml
  when:
    - (web_app_full_wipe is undefined) or (web_app_full_wipe != "true")
  tags:
    - app_setup
- name: Wipe web app
  import_tasks: wipe.yml
  when: 
    - (web_app_full_wipe is defined) and (web_app_full_wipe == "true")
  tags:
    - wipe
