---
- name: Install application
  include_tasks: "install.yml"
  when: "web_app_full_wipe is not defined"

- name: Wipe appliction
  include_tasks:
    file: "0-wipe.yml"
  tags: wipe
  when: "web_app_full_wipe is defined"