---
# tasks file for ./roles/web_app

- name: Include wipe_containers
  # Include a task file to delete Docker containers
  tags: wipe
  block: 
    - name: Include wipe_containers
      ansible.builtin.include_tasks:
        file: wipe_containers.yml
  when: web_app_full_wipe == true

- name: Move docker-compose to the target
  # Move the docker-compose template to the target location
  tags: move
  template:
    src: docker-compose.yml.j2
    dest: ~/docker-compose.yml

- name: Include build_docker
  # Include a task file to build the Docker image
  tags: build
  ansible.builtin.include_tasks:
    file: build_docker.yml
