---
- include_tasks: deploy.yml
  tags: 
    - app-deploy

- include_tasks: wipe.yml
  when: wipe_logic == true
  tags:
    - app-wipe

- name: Ensure web app is running
  docker_container:
    name: "{{ container_name }}"
    state: started
    
  tags:
    - app-started
