- name: start container
  tags:
    - start_container
  block:
    - name: pull image
      docker_image:
        name: "{{ my_image }}"
        source: pull

    - name: start app
      docker_container:
        name: "{{ container_name }}"
        image: "{{ my_image }}"
        state: started
        ports:
          - "{{ external_port }}:{{ internal_port }}"

- name: create docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ dc_path }}"
