- block:
  - name: Stop and remove Docker conainer
    docker_container:
      name: "{{ container_name }}"
      state: absent

  - name: Remove Docker image  
    docker_image:
      name: "{{ image }}"
      state: absent

  tags:
    - app-wipe
