- name: Stop container if it exists
  block:
    - name: Stop container
      tags: wipe
      # Stop the Docker container if it exists
      community.docker.docker_container:
        name: "{{container_name}}"
        state: stopped
  rescue:
    - name: Failed to stop container
      # Handle any errors that occur while stopping the container
      debug:
        msg: Failed to stop container

- name: Delete container if it exists
  block:
    - name: Delete container
      tags: wipe
      # Delete the Docker container if it exists
      community.docker.docker_container:
        name: "{{container_name}}"
        state: absent
  rescue:
    - name: Failed to delete container
      # Handle any errors that occur while deleting the container
      debug:
        msg: Failed to delete container

- name: Delete image if it exists
  block:
    - name: Delete image
      tags: wipe
      # Delete the Docker image if it exists
      community.docker.docker_image:
        name: "{{docker_image}}"
        state: absent
  rescue:
    - name: Failed to delete image
      # Handle any errors that occur while deleting the image
      debug:
        msg: Failed to delete image
