apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rust
  labels:
    app: app-rust
    {{- include "library-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-rust
      {{- include "library-chart.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: app-rust
        {{- include "library-chart.labels" . | indent 8 }}
    spec:
      containers:
        - name: app-rust
          image: ilyasiluyanov/app_rust:dev
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
