apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
      - name: python-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
          # {{- include "python-app.envVars" . | nindent 12 }}
          - name: "PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: "USERNAME"
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username