# templates/post-install-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-post-install"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: post-install
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Post-install hook is running && sleep 20']
