# templates/pre-install-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-pre-install"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: pre-install
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Pre-install hook is running && sleep 20']
