apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-django-app.fullname" . }}
  labels:
    {{- include "my-django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "my-django-app.selectorLabels" . | nindent 4 }}
