- name: Deploy go app
  hosts: all
  become: yes
  roles:
    - name: web_app
      vars:
        docker_container: 'art22m-container-goapp'
        docker_image_name: 'art22m/goapp'
        docker_image_version: 'latest'

        internal_port: 9000
        external_port: 9000

        web_app_name: 'goapp' 