version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  promtail:
    image: grafana/promtail:2.9.2
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
