version: "3"

networks:
  loki:

x-healthcheck: &hc
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 5s

services:
  app_python:
    image: zrrrget/app_python
    ports:
      - "8000:8000"
    logging: &runtime_log
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m"
        max-file: "3"
    networks:
      - loki
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:8000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 512m

  app_bash:
    image: zrrrget/app_bash
    ports:
      - "9000:9000"
    logging:
      <<: *runtime_log
    networks:
      - loki
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:9000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 512m

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      <<: *runtime_log
    healthcheck:
      <<: *hc
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:3100/ready || exit 1
    deploy:
      resources:
        limits:
          memory: 512m

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      <<: *runtime_log
    healthcheck:
      <<: *hc
      test:
        - CMD-SHELL
        - timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9080' || exit 1
    deploy:
      resources:
        limits:
          memory: 512m

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      <<: *runtime_log
    healthcheck:
      <<: *hc
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:3000/api/health || exit 1
    deploy:
      resources:
        limits:
          memory: 512m

  prometheus:
    logging:
      <<: *runtime_log
    image: prom/prometheus:v2.45.1
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loki
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - '9090:9090'
    healthcheck:
      <<: *hc
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:9090/-/healthy || exit 1
    deploy:
      resources:
        limits:
          memory: 512m

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 512m