version: "3"

networks:
  loki:

services:
  app_python:
    image: sl1depengwyn/python_devops:latest
    ports:
      - "80:80"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "10m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  app_elixir:
    image: sl1depengwyn/elixir_devops:latest
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "10m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "10m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "10m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_LOG_MODE=console file
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=true
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=true
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config/provisioning:/etc/grafana/provisioning
      - ./grafana/logs:/var/log/grafana
    deploy:
      resources:
        limits:
          memory: 500M

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
        max-size: "10m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: 500M
