version: "3"

networks:
  loki:

services:
  app_python:
    image: thecarrot/whataretime:latest
    volumes:
      - ./logs/:/code/log/
    ports:
      - 5000:8000

  grafana:
    image: grafana/grafana:9.1.6
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./logs/:/var/log/
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki

  loki:
    image: grafana/loki:2.7.0
    ports:
      - "3100:3100"

    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - loki

volumes:
  grafana:
