version: "3"

networks:
  loki:
    name: loki

services:
  app_python:
    image: nikitosing/app_python
    ports:
      - "80:80"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m" # Set log rotation size to 10MB
        max-file: "3" # Keep up to 3 log files
    deploy:
      resources:
        limits:
          memory: 256M # Set a memory limit of 256MB
    healthcheck:
      test: "curl -f http://localhost/ || exit 1" 
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./visits/python:/app/visits

  app_elixir:
    image: nikitosing/app_elixir
    ports:
      - "81:4000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m" # Set log rotation size to 10MB
        max-file: "3" # Keep up to 3 log files
    environment:
      - SECRET_KEY_BASE='WPcE2F5vjA5X3XBE+QcK7OHMiAuPovP4e62Gsl0VFxRHvu+xS2AiQWY0H3Qz6Q3O'
    deploy:
      resources:
        limits:
          memory: 256M # Set a memory limit of 256MB
    healthcheck:
      test: "curl -f http://localhost:4000/time || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./visits/elixir:/app/visits
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m" # Set log rotation size to 10MB
        max-file: "3" # Keep up to 3 log files
    deploy:
      resources:
        limits:
          memory: 256M # Set a memory limit of 256MB

  promtail:
    image: grafana/promtail:latest
    volumes:
      # - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m" # Set log rotation size to 10MB
        max-file: "3" # Keep up to 3 log files
    deploy:
      resources:
        limits:
          memory: 256M # Set a memory limit of 256MB

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - loki
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m" # Set log rotation size to 10MB
        max-file: "3" # Keep up to 3 log files
    deploy:
      resources:
        limits:
          memory: 256M # Set a memory limit of 256MB

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - /run.sh
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m" # Set log rotation size to 10MB
        max-file: "3" # Keep up to 3 log files
    deploy:
      resources:
        limits:
          memory: 256M # Set a memory limit of 256MB
