version: "3"

networks:
  loki:

services:
  web_app:
    hostname: web_app
    image: evalekalek/devops:latest
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    restart: always
    ports:
      - "8000:8000"
    logging: &logger
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 10
        tag: "{{.ImageName}}|{{.Name}}|{{.FullID}}"

  loki:
    image: grafana/loki:2.9.2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      <<: *logger

  promtail:
    image: grafana/promtail:2.9.2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      <<: *logger

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    ports:
      - "9090:9090"
    networks:
      - loki
    logging:
      <<: *logger

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          basicAuth: false
          isDefault: false
          editable: true
        EOF
        /run.sh
    image: grafana/grafana:latest
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      <<: *logger