scrape_configs:
  - job_name: 'app_loki'
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ['loki:3100']
    basic_auth:
      username: user123
      password: pass321word
  - job_name: "app_prometheus"
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: [ 'prometheus:9090' ]
    basic_auth:
      username: user123
      password: pass321word
  - job_name: "app_promtail"
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: [ 'promtail:9080' ]
    basic_auth:
      username: user123
      password: pass321word
  - job_name: "app_grafana"
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: [ 'grafana:3000' ]
    basic_auth:
      username: user123
      password: pass321word
