global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: python_app
    static_configs:
      - targets:
          - python_app:8000

  - job_name: go_app
    static_configs:
      - targets:
          - go_app:9000

  - job_name: loki
    honor_timestamps: true
    scrape_interval: 5s
    static_configs:
      - targets:
          - loki:3100

  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080

  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000

  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090