global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: loki
    honor_timestamps: true
    scrape_interval: 5s
    static_configs:
      - targets:
          - loki:3100

  - job_name: app_python
    static_configs:
      - targets:
          - app_python:8008

  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080

  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000

