apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  labels:
    app: python-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - name: python-web
        image: zrrrget/app_python
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-web-app
  labels:
    app: bash-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bash-web-app
  template:
    metadata:
      labels:
        app: bash-web-app
    spec:
      containers:
      - name: bash-web-app
        image: zrrrget/app_bash
        ports:
        - containerPort: 9000