apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: "apps.info"
    http:
      paths:
      - path: /python
        pathType: Prefix
        backend:
          service:
            name: app-python
            port:
              number: 80
      - path: /js
        pathType: Prefix
        backend:
          service:
            name: app-js
            port:
              number: 80
