apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: moscow.time
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python
                port:
                  number: 80
    - host: base.converter
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-kotlin
                port:
                  number: 8080