apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /time
spec:
  rules:
    - host: app.py
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python-service
                port:
                  number: 80
    - host: app.go
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-go-service
                port:
                  number: 80