apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: python.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python
                port:
                  number: 80

    - host: elixir.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-elixir
                port:
                  number: 4000