password: ENC[AES256_GCM,data:ZawCuReA,iv:PrAsugz5y/snb4+b88JsgPxSm5FKFelK+c1xe3xNdGU=,tag:qwe1QHvBjL5i3T7lVwcclw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T21:54:28Z"
    mac: ENC[AES256_GCM,data:oYpvjRaf6PunQWLixnaiCLNhftJ08wPgFttp0vV8pkhXgPApMOv/HTNo7OmOwD+HztAvrMSPXRSJJQeGaEO3MJ0CA35ZsRpXMK+a8mQzObD7DZd4OvGzM/Fs3B6aCoOaYjtS8AB3D2paRB1KRige51/uTyhdtCbQbsULsqM+ryA=,iv:evq/nOqq0gY30TDhZ8utL04kvnakwxqNBJT88PgfnFE=,tag:dBqEOIUyszc3LtXm5Rr+vQ==,type:str]
    pgp:
        - created_at: "2023-11-14T21:52:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D3pE6Or5ZOQcSAQdA67WQm31njCHnJsYVks36HJl4qjLvuc9OmZPb8yS4cQow
            aVDIJuxT1HVGGfkRHt7LEZuEkQEr3lSNMgPLZx5+yWsNktqQalGm7HtYJs0GA7t7
            1GgBCQIQu1xZKWmgd0tJV78YKMfX8R5in509xV+3U+JAhWR8Qo8mVIWsHDO1YLAp
            X8vmfx6SjXaZZ2Q5h5znXQuMAIRHGUounHh+f4OPVmYgI2TdFvnqhesGYRdmpZbn
            yzeb5OANagIkQg==
            =wF6K
            -----END PGP MESSAGE-----
          fp: A6A490E82A7938118D1CD0C3BEABD28CBF0A6FFE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
