apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-python
  name: app-python
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.229.12
  clusterIPs:
  - 10.108.229.12
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31829
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-python
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.108.229.12