apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-web-serv
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: js-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: js-web-serv
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
