apiVersion: v1
kind: Service
metadata:
  name: python-web-app
spec:
  type: NodePort
  selector:
    app: python-web-app
  ports:
    - nodePort: 31685 # access service via this port
      port: 80 # internally in cluster
      targetPort: 80 # container listening
