apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: app_python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: app_go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
