apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-react-swapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ts-react-swapi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ts-react-swapi-service
                port:
                  number: 5173
