apiVersion: v1
kind: Service
metadata:
  name: ts-react-swapi-service
spec:
  selector:
    app: ts-react-swapi
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30001
  type: NodePort
