server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true