---
- name: Deploy Python app in Docker
  hosts: all
  become: yes
  roles:
    - name: web_app
      vars:
        docker_container: 'app_python'
        docker_image_name: 'lnsfna/app_python'
        docker_image_version: 'latest'
        internal_port: 8080
        external_port: 8080
        app_name: 'app_python'