apiVersion: v1
data:
  secretK: c2VjcmV0
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: python-helm-app
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-14T16:42:01Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-secret
  namespace: default
  resourceVersion: "17809"
  uid: d77b089e-ece4-41c5-8106-119ff82bb4df
type: Opaque

