name: app_dart
description: Simple Jaguar web app that displays current time in Moscow
version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner:
  lints: ^2.0.0
dependencies:
  jaguar: ^2.0.0
