global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
- job_name: docker
  # use docker.sock to filter containers
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      refresh_interval: 5s
      filters:
        - name: label
          values: ["com.docker.compose.project=monitoring"]
  # use container name to create a loki label
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
