scrape_configs:
  - job_name: "node"
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: "loki"
    scrape_interval: 5s
    static_configs:
    - targets: ['loki:3100']
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: "promtail"
    scrape_interval: 5s
    static_configs:
      - targets: ['promtail:9080']
  - job_name: "grafana"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'grafana:3000' ]