apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app_python
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  token: {{ .Values.token | b64enc | quote }}