apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"component":"apiserver","provider":"kubernetes"},"name":"kubernetes","namespace":"default"},"spec":{"ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":8443}],"type":"ClusterIP"},"status":{"loadBalancer":{}}}
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
  spec:
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: lab-node-kotlin
    name: lab-node-kotlin
  spec:
    allocateLoadBalancerNodePorts: true
    ports:
    - nodePort: 30130
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: lab-node-kotlin
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
