- name: Ping all hosts
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

- name: Deploy docker from galaxy
  hosts: all
  become: yes
  roles:
    - geerlingguy.docker

- name: Deploy docker from scratch
  hosts: all
  become: yes
  roles:
    - docker
