- name: health check
  hosts: all
  tasks:
  - name: Ping all hosts
    ansible.builtin.ping:

  - name: Update all apt packages
    apt:
      update_cache: yes
    become: yes

- name: Deploy geerlingguy.docker
  become: yes
  hosts: all
  roles:
    - geerlingguy.docker

- name: Deploy custom docker
  become: yes
  hosts: all
  roles:
    - docker
