---
- name: Deploy App go on Yandex Cloud Virtual Machine
  hosts: inventory/dev
  become: true

  vars:
    app_directory: /opt/app_go
    timezone: UTC
    web_app_full_wipe: false
    image: bobievnodir/app_go:latest
    container_name: app_go
    ports: "8080:8080"

  roles:
    - web_app
