- name: Check docker version
  ansible.builtin.shell:
    cmd: python3 -c "import docker; print(docker.__version__)"
  register: docker_version

- name: Check docker-compose version
  ansible.builtin.shell:
    cmd: docker-compose --version
  register: docker_compose_version

- name: Display docker version
  debug:
    msg: "{{ docker_version.stdout }}"

- name: Display docker-compose version
  debug:
    msg: "{{ docker_compose_version.stdout }}"
