# Updating Apt
- name: Update apt
  apt:
    update_cache: true

# Using Apt to install Python and Pip
- name: Install python and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present
