---

# Note: update_cache will be passed to the underlying module.
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
# Note: docker.io was preferred over docker-ce due to the maintainability 
- name: "Install Docker"
  package:
    name: 'docker.io'
    state: latest
    update_cache: yes
