---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update package index files
  apt:
    update_cache: yes

- name: Install latest Docker CE
  apt:
    name: docker-ce
    state: latest
    update_cache: true
