- name: Install pip
  ansible.builtin.include_tasks:
    file: install_pip.yaml

- name: Install docker
  ansible.builtin.include_tasks:
    file: install_docker.yaml

- name: Install docker-compose
  ansible.builtin.include_tasks:
    file: install_docker_compose.yaml