- name: Install pip
  import_tasks: install_pip.yml
  tags:
    - docker
- name: Install docker
  import_tasks: install_docker.yml
  tags:
    - docker
- name: Install docker compose
  import_tasks: install_compose.yml
  tags:
    - docker
