- name: Install pip
  ansible.builtin.include_tasks:
    file: install_pip.yml

- name: Install repo
  ansible.builtin.include_tasks:
    file: install_docker_repo.yml

- name: Install docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Install docker-compose
  ansible.builtin.include_tasks:
    file: install_compose.yml
  when: docker_install_compose_plugin | bool