---
- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker and Docker Compose using pip
  pip:
    name:
      - docker
      - docker-compose
    state: present
