---
- name: Install pip
  apt:
    name:
      - python3-pip

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install docker-compose
  pip:
    name:
      - docker-compose
      - docker
    state: latest

- name: Check current docker state
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes