apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_python
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: app_python
        image: justsomedude22/app_python
        ports:
        - containerPort: 5000 