apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: IlyaMirzazhanov/python-app:latest
        ports:
        - containerPort: {{ .Values.service.port }}
          name: app-python-port
    volumeMounts:
        - name: configuration
          readOnly: true
          mountPath: "/config.json"
          subPath: config.json
  volumes:
        - name: configuration
          configMap:
            name: myconfigmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}