name: python-app

on:
  push:
    paths:
      - '.github/workflows/app-python-ci.yaml'
      - 'app_python/**'

defaults:
  run:
    working-directory: ./app_python

jobs:
  checks:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: ./app_python/requirements.txt
          
      - name: Dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
        
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          python ./src/test.py

      - uses: snyk/actions/setup@master
      - name: Snyk test for vulnerabilities
        continue-on-error: true
        run: | 
          snyk test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build_deploy:
    needs: checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Buildx setup
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        run: |
            docker buildx build -t artkochergin/devops-course:app_python .
            docker buildx build --push -t artkochergin/devops-course:app_python .
        working-directory: ./app_python
