name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./app_python/requirements.txt

    - name: Lint with flake8
      run: flake8 ./app_python/.

    - name: Test with pytest
      run: pytest ./app_python/test.py


    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.9@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --workdir app_python --all-projects -- --allow-missing
    

    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app_python
        file: ./app_python/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dev-ops-lab-3:latest