on:
  push:
    paths:
      - lab01/app_python/**

defaults:
  run:
    working-directory: lab01/app_python

jobs:
  build-and-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest tests
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Run ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.0.287
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: lab01/app_python
          push: true
          tags: ilyasiluyanov/app_python:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
  security:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - uses: snyk/actions/setup@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - 
        name: Run snyk
        run: |
          pip install -U pip
          pip install -r requirements.txt
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
