name: CI (Python)

on:
  push:
    branches:
      - main
    paths:
      - "app_python/**"
      - ".github/workflows/app_python.yaml"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Build
        run: |
          pip install pylint pytest
          pip install -r app_python/requirements.txt
      - name: Lint
        run: pylint app_python --ignore=venv
      - name: Test
        run: pytest app_python

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: el3os
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - id: vars
        run: echo "::set-output name=tagname::$(git rev-parse --short HEAD)"
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: app_python/
          file: app_python/Dockerfile
          push: true
          tags: el3os/moscow_time_python:${{ steps.vars.outputs.tagname }} , el3os/moscow_time_python:latest
          cache-from: type=registry,ref=el3os/moscow_time_python:latest
          cache-to: type=inline

  scan-valnurabilities:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: el3os/moscow_time_python
