ame: Python package

on:
  push:
    paths:
    - 'app_pyton/myproject/**'
  commit:
    paths:
    - 'app_pyton/myproject/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r ./app_python/requirements.txt
      working-directory: app_python/myproject

      - name: Lint using ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      working-directory: app_python/myproject