name: Python App
run-name: Test & Build Python App
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest httpx
          pytest -v
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint *.py
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --severity-threshold=critical
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build:
    needs: [test, security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_python
          push: true
          tags: amoriodi/app_python:latest
