name: Go CI

on:
  push:
    paths:
      - 'app_go/**'
      - '.github/workflows/go-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Dependencies
        working-directory: ./app_go
        run: go mod download

      - name: Linter
        run: go vet app_go/app.go

      - name: Tests
        working-directory: ./app_go
        run: go test -v .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-go-app ./app_go
          docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app

      - name: Snyk Security Check
        run: npx snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: go-modules-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-modules-${{ runner.os }}-


