name: app_bash CI

on:
  push:
    paths:
      - 'app_bash/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install shellcheck nmap ncat curl
      - name: Lint with shellcheck
        run: |
          shellcheck app_bash/*.sh
        continue-on-error: true
      - name: Test
        run: |
          cd app_bash && ./test.sh && cd -
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build and run tests
        uses: docker/build-push-action@v5
        with:
          context: ./app_bash
          file: app_bash/Dockerfile
          target: test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_bash_test
      - name: Test
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/app_bash_test         
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app_bash
          file: app_bash/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_bash

