name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
      uses: actions/setup-python@v41
      with:
        python-version: '3.11'
        cache: 'pip'
      - name: Install dependencies
      run: python -m pip install --upgrade pip
      run: pip install -r requirements.txt
      - uses: chartboost/ruff-action@v1
      with:
        src: "./src"
        args: --format github --target-version py311

      - name: Test with pytest
      run: pip install pytest
      run: pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

      - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_python_ci:latest

