# name: GitHub Actions
# run-name: Test, build & push
# on: [push]

# jobs:
#   security:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: snyk/actions/setup@master
#       - uses: actions/setup-go@v1
#         with:
#           go-version: '1.19'
#       - name: Snyk test
#         run: |
#           cd app_python
#           pip install -r requirements.txt
#           snyk test
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

#   test:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./app_python


#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Run tests
#         run: python -m unittest tests.test

#   build-and-push:
#     needs: [security, test]
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Log in to Docker registry
#         uses: docker/login-action@v3
#         with:
#           # registry: <your-docker-registry>  # Replace with your container registry URL
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: app_python
#           push: true
#           tags: ${{ secrets.DOCKER_IMAGE }}:latest
#           cache-from: type=registry,ref=user/app:latest
#           cache-to: type=inline
