name: Golang CI

on:
  push:
    paths:
      - '.github/workflows/golang_ci.yml'
      - 'app_golang/**'

defaults:
  run:
    shell: bash
    working-directory: app_golang

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.0'

    - name: Tests
      run: go test -v ./...

  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: snyk/actions/setup@master
      - name: Snyk test for vulnerabilities
        continue-on-error: true
        run: |
          snyk test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: app_golang/snyk.sarif
          category: snyk-golang

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_golang
          file: app_golang/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webservicego:0.0.2