name: Python CI

on:
  pull_request:
    types:
      - opened
      - synchronize 

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -r requirements.txt

      - name: Run linter
        run: black .

      - name: Run tests
        run: python -m unittest test_app.py

  docker_build_push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: app_python
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moscow-time:latest