name: PR Testing and Building

on:
  pull_request:
    # branches:
    #   - main
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black
      
      - name: Linter
        run: black .
      
      - name: Tests
        run: python -m unittest main/tests.py


  push_docker:
    runs-on: ubuntu-latest
    needs: test
    # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: app_python
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/whataretime:latest
        