name: Node.js CI

on:
  push:
    paths:
      - 'app_node/**'
      - '.github/workflows/node-ci.yml'
  pull_request:
    paths:
      - 'app_node/**'
      - '.github/workflows/node-ci.yml'

defaults:
  run:
    working-directory: ./app_node # Set the default directory of the Node.js project

jobs:

  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your preferred Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Lint with ESLint
        run: |
          npx eslint .

      - name: Run tests
        run: |
          npx mocha test.js

  security-check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif

  build-and-push:
      needs: [lint-and-test, security-check]
      runs-on: ubuntu-latest

      steps:

        - name: Checkout code repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          run: |
            docker buildx build -t artkochergin/random-node-app:latest .
            docker buildx build --push -t artkochergin/random-node-app:latest .
          working-directory: ./app_node # Change to your project directory