name: Python CI

# on:
#   push:
#     paths:
#       - "app_python/**"
on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: ./app_python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: flake8 . --per-file-ignores="test/conftest.py:E402"

      - name: Run Tests
        run: pytest

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
            --package-manager=pip
            --file=requirements.txt

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t nikitosing/app_python:latest ./app_python
          docker push nikitosing/app_python:latest

      # - name: Install Snyk CLI
      #   run: npm install -g snyk

      # - name: Scan for Vulnerabilities
      #   run: snyk test --all-projects
