name: Python workflow

on:
  push:
    paths:
    - 'app_python/**'
    - '.github/workflows/python.yml'
  pull_request:
    paths:
    - 'app_python/**'
    - '.github/workflows/python.yml'

defaults:
  run:
    working-directory: ./app_python

jobs:
  build-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
    - name: Checkout repo.
      uses: actions/checkout@v3

    - name: Install dependencies.
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          ./requirements-base.txt
          ./requirements-dev.txt

    - name: Lint with pre-commit.
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: flake8 black isort black

    - name: Test with pytest.
      run: |
        pytest
