name: Python workflow

on:
  push:
    paths:
    - 'app_python/**'
    - '.github/workflows/python.yml'
    - '.pre-commit-config.yaml'
  pull_request:
    paths:
    - 'app_python/**'
    - '.github/workflows/python.yml'
    - '.pre-commit-config.yaml'

defaults:
  run:
    working-directory: ./app_python

jobs:
  build-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
    - name: Checkout repo.
      uses: actions/checkout@v3

    - name: Install dependencies.
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'
        cache-dependency-path: |
          ./app_python/requirements-base.txt
          ./app_python/requirements-dev.txt

    - name: Lint with bandit.
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: bandit --all-files

    - name: Lint with flake8.
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: flake8 --all-files

    - name: Lint with black.
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: black --all-files

    - name: Lint with isort.
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: isort --all-files

    - name: Test with pytest.
      run: |
        pipenv run pytest
