name: Python CI

on:
  push:
    paths:
      - 'app_python/**' # Run only when changes occur in the app_python folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # Choose your desired Python version

    - name: Install Dependencies
      run: pip install -r app_python/requirements.txt

    - name: Lint
      run: flake8 app_python

    - name: Run Tests
      run: pytest app_python

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t nikitosing/app_python:latest ./app_python
        docker push nikitosing/app_python:latest

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Scan for Vulnerabilities
      run: snyk test --all-projects
